name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to docker registry
      uses: docker/login-action@v3
      with:
        registry : harbor.m-loeffler.de
        username: ${{ secrets.HARBOR_ROBOT_NAME }}
        password: ${{ secrets.HARBOR_ROBOT_SECRET }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        push: true
        tags: harbor.m-loeffler.de/testapps/react:latest